import type { Article, FounderTool, Playbook, Template } from "./types";

const moduleDescriptions: Record<string, string> = {
  "Clarify the idea": "Turn the rough thought into a clear customer, promise, and first offer.",
  "Define the customer": "Name the buyer, the context, and the problem they already care about.",
  "Build the first visual version in Lovable": "Use Lovable to make the idea visible before overinvesting in polish.",
  "Create the offer": "Shape the first package, price logic, and reason to buy now.",
  "Structure the website": "Map the homepage, service pages, proof points, and conversion path.",
  "Buy the domain": "Secure a credible web address early so the business has a serious home.",
  "Set up hosting": "Choose simple hosting that can support a professional first version.",
  "Create professional email": "Move from casual inboxes to domain-based communication.",
  "Create social profiles": "Claim the right handles across Facebook, Instagram, and LinkedIn.",
  "Launch the first test": "Publish the lean version and route traffic into one measurable action.",
};

const makeModules = (titles: string[], prefix: string) =>
  titles.map((title, index) => ({
    id: `${prefix}-${index + 1}`,
    title,
    description:
      moduleDescriptions[title] ||
      `A practical operating step for ${title.toLowerCase()} without adding unnecessary complexity.`,
    type: index % 3 === 0 ? ("checklist" as const) : ("guide" as const),
  }));

export const playbookCategories = ["Setup", "Presence", "Validation", "AI", "Growth", "Pitching", "Operations"];

export const playbooks: Playbook[] = [
  {
    id: "pb-idea-digital-business",
    title: "Idea to Digital Business",
    slug: "idea-to-digital-business",
    summary: "Turn a rough idea into a live digital business concept with a website, domain, offer, and launch checklist.",
    category: "Setup",
    difficulty: "Starter",
    estimatedTime: "7–10 focused days",
    outcome: "A credible first version of the business that can be shown, tested, and improved.",
    modules: makeModules([
      "Clarify the idea",
      "Define the customer",
      "Build the first visual version in Lovable",
      "Create the offer",
      "Structure the website",
      "Buy the domain",
      "Set up hosting",
      "Create professional email",
      "Create social profiles",
      "Launch the first test",
    ], "idea"),
    toolsNeeded: ["Lovable", "Domain registrar", "Website hosting", "Google Workspace or equivalent", "Meta Business Suite", "WhatsApp Business"],
    templatesIncluded: ["Business Idea Clarity Sheet", "Website Homepage Structure", "Domain & Email Setup Checklist", "Launch Readiness Score"],
    featured: true,
    accessLevel: "free",
  },
  {
    id: "pb-online-presence",
    title: "Building Your Online Presence",
    slug: "building-your-online-presence",
    summary: "Make your business look real online before trying to sell seriously.",
    category: "Presence",
    difficulty: "Starter",
    estimatedTime: "3–5 days",
    outcome: "Consistent public profiles that make the business easier to trust, search, and share.",
    modules: makeModules(["Naming consistency", "Brand bio", "Facebook page setup", "Instagram setup", "LinkedIn setup", "Founder profile optimization", "Timeline/feed curation", "Pinned posts", "Highlights", "Trust signals"], "presence"),
    toolsNeeded: ["Facebook", "Instagram", "LinkedIn", "Canva or brand assets", "WhatsApp Business"],
    templatesIncluded: ["Social Profile Audit", "Timeline Curation Checklist", "Brand Bio Builder"],
    featured: true,
    accessLevel: "email-gated",
  },
  {
    id: "pb-email-identity",
    title: "Business Email & Professional Identity",
    slug: "business-email-professional-identity",
    summary: "Set up the communication layer that makes your business look serious.",
    category: "Presence",
    difficulty: "Starter",
    estimatedTime: "2–4 days",
    outcome: "A clean communication system for inquiries, booking, proposals, and follow-up.",
    modules: makeModules(["Domain-based email", "Email aliases", "Signature setup", "Contact structure", "Inquiry forms", "Booking links", "Proposal emails", "Follow-up emails", "Cold outreach basics", "Email credibility"], "email"),
    toolsNeeded: ["Google Workspace", "Calendly or booking tool", "Website forms", "CRM-ready spreadsheet"],
    templatesIncluded: ["Domain & Email Setup Checklist", "Proposal Email Template", "Lead Follow-Up Script"],
    featured: true,
    accessLevel: "free",
  },
  {
    id: "pb-google-local-seo",
    title: "Google Presence & Local SEO",
    slug: "google-presence-local-seo",
    summary: "Set up your Google presence so customers can actually find and trust you.",
    category: "Growth",
    difficulty: "Focused",
    estimatedTime: "2–3 weeks",
    outcome: "A search-ready local presence built around trust, reviews, and clear service pages.",
    modules: makeModules(["Google Business Profile", "Reviews", "Categories", "Photos", "Local keywords", "Service pages", "Multi-location strategy", "Multi-country landing pages", "Ranking for service searches", "Tracking performance"], "google"),
    toolsNeeded: ["Google Business Profile", "Google Search Console", "Google Analytics", "Keyword planner", "Review request process"],
    templatesIncluded: ["Google Business Profile Checklist", "Review Request Scripts", "Multi-Country SEO Map"],
    featured: true,
    accessLevel: "email-gated",
  },
  {
    id: "pb-ads-before-build",
    title: "Ads Before You Build",
    slug: "ads-before-you-build",
    summary: "Use Meta ads and simple landing pages to test market interest before overbuilding.",
    category: "Validation",
    difficulty: "Focused",
    estimatedTime: "10–14 days",
    outcome: "A real signal on demand before the business spends serious money building the wrong thing.",
    modules: makeModules(["Why validation beats guessing", "Landing page test", "Offer test", "Meta ad setup", "Lead capture", "WhatsApp follow-up", "Reading the data", "Avoiding fake demand", "Deciding whether to build", "Scaling what works"], "ads"),
    toolsNeeded: ["Meta Ads Manager", "Landing page builder", "WhatsApp Business", "Lead tracker", "Basic analytics"],
    templatesIncluded: ["Meta Ad Test Tracker", "Lead Follow-Up Script", "Offer Test Scorecard"],
    featured: true,
    accessLevel: "paid",
  },
  {
    id: "pb-ai-setup",
    title: "AI Setup for Entrepreneurs",
    slug: "ai-setup-for-entrepreneurs",
    summary: "Build an AI interface tailored to your business so you can move like a larger team.",
    category: "AI",
    difficulty: "Focused",
    estimatedTime: "4–6 days",
    outcome: "A practical AI workspace for proposals, captions, SOPs, sales emails, and customer scripts.",
    modules: makeModules(["Setting up ChatGPT for your business", "Custom prompts", "Proposal templates", "Caption systems", "Customer service scripts", "SOP creation", "Hiring assistant", "Offer creation", "Sales emails", "Automation basics"], "ai"),
    toolsNeeded: ["ChatGPT", "Prompt vault", "Business context document", "Automation notes"],
    templatesIncluded: ["AI Business Setup Prompt", "SOP Template", "Proposal Email Template"],
    featured: true,
    accessLevel: "email-gated",
  },
  {
    id: "pb-pitch-setup",
    title: "Business Plan & Pitch Setup",
    slug: "business-plan-pitch-setup",
    summary: "Create practical business plans, pitch decks, and pitch videos that funders can understand.",
    category: "Pitching",
    difficulty: "Advanced",
    estimatedTime: "2–4 weeks",
    outcome: "A grant- and investor-ready explanation of what the business does, why it matters, and how funds will be used.",
    modules: makeModules(["One-page business plan", "Pitch deck structure", "Grant application structure", "Use-of-funds planning", "Revenue model", "Market opportunity", "Problem and solution", "Competitive advantage", "Founder story", "Pitch video setup"], "pitch"),
    toolsNeeded: ["Pitch deck software", "Financial model spreadsheet", "Grant criteria", "Video recording setup"],
    templatesIncluded: ["Business Plan Outline", "Pitch Deck Outline", "Pitch Video Script"],
    featured: false,
    accessLevel: "paid",
  },
];

export const templateCategories = ["Website Setup", "Social Media", "Email", "Google Business Profile", "Ads", "Pitching", "AI Prompts", "Business Planning", "Operations"];

export const templates: Template[] = [
  ["Business Idea Clarity Sheet", "Business Planning", "A focused worksheet for turning a loose idea into a customer, offer, and next action."],
  ["Website Homepage Structure", "Website Setup", "A premium homepage outline built around clarity, trust, and conversion."],
  ["Domain & Email Setup Checklist", "Email", "A step-by-step setup list for domain purchase, inbox structure, aliases, and signatures."],
  ["Social Profile Audit", "Social Media", "A practical check for whether your public profiles look active, credible, and aligned."],
  ["Timeline Curation Checklist", "Social Media", "A founder-facing checklist for cleaning the feed before serious outreach."],
  ["Google Business Profile Checklist", "Google Business Profile", "A setup checklist for categories, photos, services, reviews, and local trust signals."],
  ["Review Request Scripts", "Google Business Profile", "Short scripts for requesting reviews without sounding desperate or robotic."],
  ["Meta Ad Test Tracker", "Ads", "A tracker for offer tests, budget, leads, WhatsApp follow-up, and decision quality."],
  ["Lead Follow-Up Script", "Ads", "Simple follow-up language for turning Caribbean ad leads into real conversations."],
  ["Business Plan Outline", "Business Planning", "A plain-English plan structure funders and partners can understand."],
  ["Pitch Deck Outline", "Pitching", "A clean deck sequence for problem, offer, market, traction, team, and use of funds."],
  ["Pitch Video Script", "Pitching", "A concise pitch video structure for grants, competitions, and partner introductions."],
  ["AI Business Setup Prompt", "AI Prompts", "A prompt framework for creating an AI interface that understands your business context."],
  ["Proposal Email Template", "Email", "A sharp proposal email structure for services, retainers, and partnerships."],
  ["SOP Template", "Operations", "A simple operating procedure format for repeatable work."],
  ["Partnership Outreach Email", "Email", "A direct outreach structure for collaborations, tourism channels, and referral partners."],
].map(([title, category, description], index) => ({
  id: `tpl-${index + 1}`,
  title,
  slug: title.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
  category,
  description,
  accessLevel: index < 4 ? "free" : index < 12 ? "email-gated" : "paid",
}));

export const tools: FounderTool[] = [
  ["Business Setup Checklist", "Check the core infrastructure: domain, email, website, social profiles, Google, WhatsApp, and launch assets.", "Available", "Setup"],
  ["Offer Builder", "Shape a clear first offer with audience, promise, deliverables, and pricing logic.", "Coming Soon", "Validation"],
  ["Social Bio Builder", "Draft clear profile bios for Facebook, Instagram, LinkedIn, and founder pages.", "Coming Soon", "Presence"],
  ["Google Profile Audit", "Review whether your Google Business Profile has the trust signals customers expect.", "Coming Soon", "Growth"],
  ["Ad Validation Tracker", "Track Meta ad tests, leads, replies, cost, and whether demand is real.", "Coming Soon", "Validation"],
  ["Pitch Outline Builder", "Turn a business idea into a funder-friendly deck structure.", "Coming Soon", "Pitching"],
  ["AI Prompt Builder", "Create reusable prompts that understand your offer, customers, and tone.", "Coming Soon", "AI"],
  ["Launch Readiness Score", "Score the business before launch so obvious gaps do not become public problems.", "Coming Soon", "Operations"],
].map(([title, description, status, category], index) => ({
  id: `tool-${index + 1}`,
  title,
  description,
  status: status as FounderTool["status"],
  category,
  slug: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
}));

export const articles: Article[] = [
  "Most businesses do not need a logo first",
  "Why I build the website before I feel ready",
  "Your social media is now part portfolio, part resume, part sales page",
  "Don’t build quietly",
  "How to make a small business look serious online",
  "Business theater vs real business",
  "Why Facebook ads still matter in the Caribbean",
  "The first ten things I do with a new business idea",
  "How to test demand before spending serious money",
  "Why professional email changes perception",
].map((title, index) => ({
  id: `article-${index + 1}`,
  title,
  slug: title.toLowerCase().replace(/[’']/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
  excerpt: [
    "A clean identity matters, but the first serious artifact is usually the offer and the place people can evaluate it.",
    "The website forces decisions. It exposes weak positioning faster than another private brainstorming session.",
    "In small markets, people inspect the founder and the business together. Your profiles are now trust infrastructure.",
    "Silent perfection is expensive. A visible test gives you feedback before your assumptions harden.",
    "Enterprise-level perception starts with consistency, clear pages, proper email, reviews, and follow-up.",
    "A business can look busy while avoiding the only thing that matters: customer demand.",
    "Meta still shapes attention across Caribbean markets, especially when paired with WhatsApp follow-up.",
    "The first moves are not glamorous. They are clarity, domain, offer, web page, profiles, search, and test traffic.",
    "Validation is not asking friends if the idea is good. It is watching what strangers do when given a clear offer.",
    "A domain-based email quietly changes how partners, customers, and funders read the business.",
  ][index],
  category: index % 3 === 0 ? "Founder Judgment" : index % 3 === 1 ? "Digital Infrastructure" : "Validation",
  body: "Placeholder article body prepared for the content system. Future versions can pull this from Supabase with rich text, author metadata, and publishing states.",
  publishedAt: `2026-0${(index % 5) + 1}-15`,
  featured: index < 3,
  accessLevel: "free",
}));

export const readingPrinciples = [
  { source: "Founder reading stack", title: "Execution discipline", description: "Prefer operating standards, clear priorities, and follow-through over inspirational planning." },
  { source: "Customer demand", title: "Build around willingness to act", description: "Use customer behavior, search intent, ads, and conversations to separate interest from politeness." },
  { source: "Positioning", title: "Make the offer easy to understand", description: "A business earns trust faster when the buyer can quickly explain who it helps and why it matters." },
  { source: "Hiring and standards", title: "Raise the operating bar early", description: "Small teams still need role clarity, strong judgment, and simple systems that prevent chaos." },
  { source: "Creative borrowing", title: "Study patterns, do not copy noise", description: "Books and frameworks are useful because they condense experience into shortcuts for better decisions." },
  { source: "Founder judgment", title: "Protect decision quality", description: "The work is choosing what to validate, what to ignore, and what deserves real investment." },
];
